/*
 * Hand Gesture Detection — Arduino Nano 33 BLE Sense + ArduCAM Mini 2MP Plus (OV2640)
 *
 * Camera wiring (identical to face detection project):
 *   VCC   -> 5V     (onboard AMS1117-3.3 LDO steps down to 3.3V for sensor)
 *   GND   -> GND
 *   SDA   -> A4     (3.3V I2C — do NOT use 5V logic)
 *   SCL   -> A5     (3.3V I2C)
 *   MOSI  -> 11     (3.3V SPI)
 *   MISO  -> 12     (3.3V SPI)
 *   SCK   -> 13     (3.3V SPI)
 *   CS    -> 10     (see CAM_CS below)
 *
 * Image pipeline (matches train_gesture_model.py preprocessing exactly):
 *   OV2640 QQVGA 160x120 RGB565
 *   -> stream FIFO row-by-row
 *   -> convert RGB565 -> grayscale (BT.601 integer luma)
 *   -> center-crop 64x64 written directly into TFLite INT8 input tensor
 *   No intermediate frame buffer — saves ~38 KB of SRAM.
 *
 * Gestures (CLASS_NAMES order from train_hagrid_tiny.py):
 *   0 = like
 *   1 = dislike
 *   2 = palm
 *
 * State machine:
 *   WAITING -> COOLDOWN -> WAITING
 *
 * Model:  hagrid_tiny_64_gray_int8.tflite converted to gesture_model.h
 * Input:  int8 [1, 64, 64, 1] grayscale
 * Output: int8 [1, 3] — dequantised to float probabilities
 *
 * Memory budget (256 KB SRAM):
 *   Tensor arena : 150 KB  (set via TENSOR_ARENA_KB in platformio.ini)
 *   Stack + heap :  ~50 KB
 *   Globals      :  ~56 KB
 */

#include <Arduino.h>
#include <Wire.h>
#include <SPI.h>

// memorysaver.h (in include/) defines OV2640_MINI_2MP_PLUS before ArduCAM
// reads it — this selects the correct sensor driver.
#include <memorysaver.h>
#include <ArduCAM.h>

// ArduCAM.h defines a 3-argument swap(type,i,j) macro that clashes with
// std::swap(a,b) used throughout C++ headers pulled in by TensorFlowLite.
// Undefine it here before those headers are included.
#ifdef swap
#undef swap
#endif

#include <TensorFlowLite.h>
#include <tensorflow/lite/micro/all_ops_resolver.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/schema/schema_generated.h>
#include <math.h>

// Generated by train_gesture_model.py step [8/8].
// Contains: gesture_model[] (uint8_t array) and gesture_model_len.
// Copy gesture_model.h into src/ alongside this file.
#include "gesture_model.h"

// =============================================================================
// Configuration
// All tunable values are injected as build flags from platformio.ini so you
// can change them without editing source code.
// =============================================================================

#define CAM_CS       10

#define CAM_WIDTH    160
#define CAM_HEIGHT   120
#define IMG_W        64
#define IMG_H        64

// Center-crop offsets: 160x120 -> 64x64
#define CROP_X       ((CAM_WIDTH  - IMG_W) / 2)   // 48 px from left
#define CROP_Y       ((CAM_HEIGHT - IMG_H) / 2)   // 28 px from top

// NUM_CLASSES, CONF_THRESH_PCT, COOLDOWN_MS are injected via build_flags.
// Provide safe defaults in case they are not set.
#ifndef NUM_CLASSES
#  define NUM_CLASSES    3
#endif
#ifndef CONF_THRESH_PCT
#  define CONF_THRESH_PCT 80
#endif
#ifndef COOLDOWN_MS
#  define COOLDOWN_MS    1500
#endif
#ifndef MARGIN_THRESH_PCT
#  define MARGIN_THRESH_PCT 15
#endif
#ifndef CONSENSUS_FRAMES
#  define CONSENSUS_FRAMES 2
#endif
#ifndef BACKGROUND_CLASS_IDX
#  define BACKGROUND_CLASS_IDX -1
#endif

static const float CONF_THRESH = CONF_THRESH_PCT / 100.0f;
static const float MARGIN_THRESH = MARGIN_THRESH_PCT / 100.0f;
constexpr uint32_t kSerialAttachTimeoutMs = 5000UL;
constexpr uint32_t kIdleReportMs          = 2000UL;

// Class labels — index order MUST match CLASS_NAMES in train_gesture_model.py
static const char* CLASS_LABELS[NUM_CLASSES] = {
    "like",
    "dislike",
    "palm"
};

// LED blink counts per gesture (D13 / built-in LED)
static const int BLINK_COUNT[NUM_CLASSES] = {
    1,   // like
    2,   // dislike
    3    // palm
};

// =============================================================================
// TFLite Micro globals
// =============================================================================

static tflite::AllOpsResolver     resolver;
static const tflite::Model*       tflModel    = nullptr;
static tflite::MicroInterpreter*  interpreter = nullptr;
static TfLiteTensor*              inputTensor  = nullptr;
static TfLiteTensor*              outputTensor = nullptr;
static int                        modelClassCount = NUM_CLASSES;

#ifndef TENSOR_ARENA_KB
#  define TENSOR_ARENA_KB 150
#endif
constexpr int kTensorArenaSize = TENSOR_ARENA_KB * 1024;
static uint8_t tensorArena[kTensorArenaSize] __attribute__((aligned(16)));

// =============================================================================
// Camera global
// =============================================================================

static ArduCAM myCAM(OV2640, CAM_CS);

// =============================================================================
// State machine
// =============================================================================

enum State { WAITING, COOLDOWN };
static State    currentState   = WAITING;
static uint32_t lastTriggerMs  = 0;
static uint32_t lastIdleReportMs = 0;
static int      candidateClass = -1;
static uint8_t  candidateCount = 0;

// Frame diagnostics: helps detect if the camera image is stuck.
static uint32_t lastFrameHash      = 0;
static uint32_t frameStableCount   = 0;
static uint16_t frameLumaMin       = 0;
static uint16_t frameLumaMax       = 0;
static float    frameLumaMean      = 0.0f;
static int8_t   frameQMin          = 0;
static int8_t   frameQMax          = 0;
static float    frameQMean         = 0.0f;
static uint32_t lastInputHash      = 0;

enum InputQuantDomain {
    INPUT_DOMAIN_0_TO_1,
    INPUT_DOMAIN_0_TO_255
};
static InputQuantDomain inputQuantDomain = INPUT_DOMAIN_0_TO_1;

static const char* tensorTypeName(TfLiteType type) {
    switch (type) {
        case kTfLiteInt8:    return "INT8";
        case kTfLiteUInt8:   return "UINT8";
        case kTfLiteFloat32: return "FLOAT32";
        default:             return "OTHER";
    }
}

static const char* inputDomainName(InputQuantDomain mode) {
    return (mode == INPUT_DOMAIN_0_TO_255) ? "0..255" : "0..1";
}

// =============================================================================
// TFLite initialisation
// =============================================================================

static bool initTFLite() {
    Serial.println(F("Initialising TFLite Micro..."));

    tflModel = tflite::GetModel(gesture_model);
    if (tflModel->version() != TFLITE_SCHEMA_VERSION) {
        Serial.println(F("ERROR: Model schema version mismatch!"));
        return false;
    }

    static tflite::MicroInterpreter staticInterpreter(
        tflModel, resolver, tensorArena, kTensorArenaSize
    );
    interpreter = &staticInterpreter;

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        Serial.println(F("ERROR: AllocateTensors() failed — arena too small."));
        Serial.print  (F("       Arena: "));
        Serial.print  (TENSOR_ARENA_KB);
        Serial.println(F(" KB. Increase TENSOR_ARENA_KB in platformio.ini."));
        return false;
    }

    inputTensor  = interpreter->input(0);
    outputTensor = interpreter->output(0);

    // Validate tensor dimensions match training config
    if (inputTensor->dims->size != 4            ||
        inputTensor->dims->data[1] != IMG_H     ||
        inputTensor->dims->data[2] != IMG_W     ||
        inputTensor->dims->data[3] != 1) {
        Serial.println(F("ERROR: Input tensor shape mismatch!"));
        Serial.print  (F("       Expected [1,64,64,1]  Got [1,"));
        Serial.print  (inputTensor->dims->data[1]); Serial.print(F(","));
        Serial.print  (inputTensor->dims->data[2]); Serial.print(F(","));
        Serial.print  (inputTensor->dims->data[3]);
        Serial.println(F("]"));
        return false;
    }

    // Confirm INT8 input type (matches training INT8 quantisation)
    if (inputTensor->type != kTfLiteInt8) {
        Serial.println(F("ERROR: Expected INT8 input tensor."));
        Serial.println(F("       Make sure you are using hagrid_tiny_64_gray_int8.tflite"));
        return false;
    }

    // Infer expected real-value domain from quant params.
    // scale ~= 1.0 typically means model expects byte-domain [0..255].
    // very small scales (e.g. ~1/255) typically mean normalised [0..1].
    inputQuantDomain = (inputTensor->params.scale >= 0.5f)
        ? INPUT_DOMAIN_0_TO_255
        : INPUT_DOMAIN_0_TO_1;

    if (outputTensor->dims->size < 1) {
        Serial.println(F("ERROR: Output tensor has invalid shape."));
        return false;
    }

    const int outputClasses = outputTensor->dims->data[outputTensor->dims->size - 1];
    if (outputClasses <= 0) {
        Serial.println(F("ERROR: Output tensor class count invalid."));
        return false;
    }

    modelClassCount = outputClasses;
    if (modelClassCount > NUM_CLASSES) {
        Serial.print(F("WARN: Model classes ("));
        Serial.print(modelClassCount);
        Serial.print(F(") exceed configured labels ("));
        Serial.print(NUM_CLASSES);
        Serial.println(F("). Truncating to configured label count."));
        modelClassCount = NUM_CLASSES;
    }

    if (modelClassCount != NUM_CLASSES) {
        Serial.print(F("WARN: Model classes ("));
        Serial.print(modelClassCount);
        Serial.print(F(") != configured NUM_CLASSES ("));
        Serial.print(NUM_CLASSES);
        Serial.println(F(")."));
    }

    Serial.print  (F("  Arena used: "));
    Serial.print  (interpreter->arena_used_bytes());
    Serial.print  (F(" / "));
    Serial.print  (kTensorArenaSize);
    Serial.println(F(" bytes"));
    Serial.print  (F("  Output type: "));
    Serial.println(tensorTypeName(outputTensor->type));
    Serial.print  (F("  Output classes used: "));
    Serial.println(modelClassCount);
    Serial.print  (F("  Input q params: scale="));
    Serial.print  (inputTensor->params.scale, 8);
    Serial.print  (F(", zero_point="));
    Serial.println(inputTensor->params.zero_point);
    Serial.print  (F("  Input real domain inferred: "));
    Serial.println(inputDomainName(inputQuantDomain));
    Serial.println(F("  TFLite ready."));
    return true;
}

// =============================================================================
// Camera initialisation (identical pattern to face detection project)
// =============================================================================

static bool initCamera() {
    Serial.println(F("Initialising ArduCAM OV2640..."));

    Wire.begin();
    SPI.begin();
    pinMode(CAM_CS, OUTPUT);
    digitalWrite(CAM_CS, HIGH);

    // Verify SPI link to ArduCAM CPLD
    uint8_t r1 = 0, r2 = 0;
    for (int attempt = 0; attempt < 3; attempt++) {
        myCAM.write_reg(ARDUCHIP_TEST1, 0x55);
        r1 = myCAM.read_reg(ARDUCHIP_TEST1);
        myCAM.write_reg(ARDUCHIP_TEST1, 0xAA);
        r2 = myCAM.read_reg(ARDUCHIP_TEST1);
        if (r1 == 0x55 && r2 == 0xAA) break;
        delay(200);
    }

    if (r1 != 0x55 || r2 != 0xAA) {
        Serial.println(F("ERROR: ArduCAM SPI not responding!"));
        Serial.println(F("  Check MOSI->11, MISO->12, SCK->13, CS->10"));
        return false;
    }

    // Verify I2C link to OV2640 sensor
    uint8_t vid = 0, pid = 0;
    myCAM.wrSensorReg8_8(0xff, 0x01);
    myCAM.rdSensorReg8_8(OV2640_CHIPID_HIGH, &vid);
    myCAM.rdSensorReg8_8(OV2640_CHIPID_LOW,  &pid);

    if (vid != 0x26 || (pid != 0x41 && pid != 0x42)) {
        Serial.print  (F("ERROR: OV2640 not found (vid=0x"));
        Serial.print  (vid, HEX);
        Serial.print  (F(", pid=0x"));
        Serial.print  (pid, HEX);
        Serial.println(F(")"));
        Serial.println(F("  Check I2C: SDA->A4, SCL->A5"));
        return false;
    }

    // QQVGA (160x120) RGB565 BMP mode — raw pixels in FIFO, no JPEG decoder needed
    myCAM.set_format(BMP);
    myCAM.InitCAM();
    myCAM.OV2640_set_JPEG_size(OV2640_160x120);
    delay(1000);   // allow AEC/AGC to settle

    Serial.println(F("  OV2640 ready (160x120 RGB565 BMP mode)."));
    return true;
}

// =============================================================================
// Frame capture + preprocessing
//
// Streams FIFO row-by-row directly into the INT8 input tensor.
// RGB565 -> grayscale using BT.601 integer luma:
//   Y = (77*R + 150*G + 29*B) >> 8
// Then normalise and quantise to INT8:
//   q = (uint8/255.0 - 0) / scale + zero_point
// No intermediate frame buffer required — saves ~38 KB SRAM.
// =============================================================================

static bool captureAndPreprocess() {
    myCAM.flush_fifo();
    myCAM.clear_fifo_flag();
    myCAM.start_capture();

    // Wait for capture-done flag (2 s timeout)
    const unsigned long deadline = millis() + 2000UL;
    while (!myCAM.get_bit(ARDUCHIP_TRIG, CAP_DONE_MASK)) {
        if (millis() > deadline) {
            Serial.println(F("ERROR: Camera capture timed out!"));
            return false;
        }
    }

    // Read quantisation params from tensor (set during INT8 conversion)
    const float   inScale  = inputTensor->params.scale;
    const int32_t inZP     = inputTensor->params.zero_point;
    int8_t* dst            = inputTensor->data.int8;
    uint16_t lumaMin       = 255;
    uint16_t lumaMax       = 0;
    uint32_t lumaSum       = 0;
    uint32_t cropCount     = 0;
    uint32_t hash          = 2166136261UL;
    int8_t   qMin          = 127;
    int8_t   qMax          = -128;
    int32_t  qSum          = 0;
    uint32_t inputHash     = 2166136261UL;

    myCAM.CS_LOW();
    myCAM.set_fifo_burst();   // positions SPI for sequential FIFO reads
    SPI.transfer(0x00);       // discard first dummy byte from burst stream

    for (int row = 0; row < CAM_HEIGHT; row++) {
        const bool rowInCrop = (row >= CROP_Y) && (row < CROP_Y + IMG_H);

        for (int col = 0; col < CAM_WIDTH; col++) {
            // Two bytes per RGB565 pixel, big-endian from ArduCAM FIFO
            const uint8_t  hi = SPI.transfer(0x00);
            const uint8_t  lo = SPI.transfer(0x00);

            if (rowInCrop && (col >= CROP_X) && (col < CROP_X + IMG_W)) {
                // Unpack RGB565 -> 8-bit channels
                const uint16_t px = ((uint16_t)hi << 8) | lo;
                const uint8_t  r  = (px >> 11) << 3;           // 5 -> 8 bits
                const uint8_t  g  = ((px >> 5) & 0x3F) << 2;   // 6 -> 8 bits
                const uint8_t  b  = (px & 0x1F) << 3;           // 5 -> 8 bits

                // BT.601 luma (integer, no float until quantisation step)
                const uint16_t luma = ((uint16_t)77 * r
                                     + (uint16_t)150 * g
                                     + (uint16_t)29  * b) >> 8;

                if (luma < lumaMin) lumaMin = luma;
                if (luma > lumaMax) lumaMax = luma;
                lumaSum += luma;
                cropCount++;

                // FNV-1a hash on luma values; fast enough and useful for
                // detecting repeated/stuck frames.
                hash ^= luma;
                hash *= 16777619UL;

                // Quantise using model's expected real-value domain.
                float realVal = luma / 255.0f;
                if (inputQuantDomain == INPUT_DOMAIN_0_TO_255) {
                    realVal = (float)luma;
                }
                int32_t q = (int32_t)roundf(realVal / inScale) + inZP;

                // Clamp to INT8 range
                if (q < -128) q = -128;
                if (q >  127) q =  127;

                const int8_t q8 = (int8_t)q;
                if (q8 < qMin) qMin = q8;
                if (q8 > qMax) qMax = q8;
                qSum += q8;
                inputHash ^= (uint8_t)q8;
                inputHash *= 16777619UL;

                *dst++ = q8;
            }
        }
    }

    myCAM.CS_HIGH();

    frameLumaMin = lumaMin;
    frameLumaMax = lumaMax;
    frameLumaMean = (cropCount > 0) ? ((float)lumaSum / (float)cropCount) : 0.0f;
    frameQMin = qMin;
    frameQMax = qMax;
    frameQMean = (cropCount > 0) ? ((float)qSum / (float)cropCount) : 0.0f;
    lastInputHash = inputHash;

    if (hash == lastFrameHash) {
        frameStableCount++;
    } else {
        frameStableCount = 0;
        lastFrameHash = hash;
    }

    return true;
}

// =============================================================================
// Inference
// Returns detected class index (0-2), or -1 for background / low confidence.
// =============================================================================

static int runInference(float* outConfidence, float* outMargin) {
    if (interpreter->Invoke() != kTfLiteOk) {
        Serial.println(F("ERROR: Invoke() failed!"));
        return -1;
    }

    float scores[NUM_CLASSES];
    const int classCount = modelClassCount;

    // Dequantise output scores to float irrespective of output tensor type.
    if (outputTensor->type == kTfLiteInt8) {
        const float   outScale = outputTensor->params.scale;
        const int32_t outZP    = outputTensor->params.zero_point;
        int8_t*       outData  = outputTensor->data.int8;
        for (int i = 0; i < classCount; i++) {
            scores[i] = (outData[i] - outZP) * outScale;
        }
    } else if (outputTensor->type == kTfLiteUInt8) {
        const float   outScale = outputTensor->params.scale;
        const int32_t outZP    = outputTensor->params.zero_point;
        uint8_t*      outData  = outputTensor->data.uint8;
        for (int i = 0; i < classCount; i++) {
            scores[i] = ((int32_t)outData[i] - outZP) * outScale;
        }
    } else if (outputTensor->type == kTfLiteFloat32) {
        float* outData = outputTensor->data.f;
        for (int i = 0; i < classCount; i++) {
            scores[i] = outData[i];
        }
    } else {
        Serial.println(F("ERROR: Unsupported output tensor type."));
        return -1;
    }

    // Handle both logits and probabilities:
    // - if values are already valid probabilities summing to ~1, keep them
    // - otherwise apply softmax to logits
    bool  looksLikeProb = true;
    float scoreSum      = 0.0f;
    for (int i = 0; i < classCount; i++) {
        if (scores[i] < 0.0f || scores[i] > 1.0f) {
            looksLikeProb = false;
        }
        scoreSum += scores[i];
    }
    if (fabsf(scoreSum - 1.0f) > 0.10f) {
        looksLikeProb = false;
    }

    float probs[NUM_CLASSES];
    if (looksLikeProb) {
        for (int i = 0; i < classCount; i++) {
            probs[i] = scores[i];
        }
    } else {
        float maxScore = scores[0];
        for (int i = 1; i < classCount; i++) {
            if (scores[i] > maxScore) maxScore = scores[i];
        }

        float expSum = 0.0f;
        for (int i = 0; i < classCount; i++) {
            probs[i] = expf(scores[i] - maxScore);
            expSum += probs[i];
        }
        if (expSum <= 0.0f) {
            Serial.println(F("ERROR: Invalid softmax normalisation."));
            return -1;
        }
        for (int i = 0; i < classCount; i++) {
            probs[i] /= expSum;
        }
    }

    int   bestIdx      = 0;
    float bestProb     = -1.0f;
    float secondBest   = -1.0f;

    for (int i = 0; i < classCount; i++) {
        const float prob = probs[i];
        if (prob > bestProb) {
            secondBest = bestProb;
            bestProb = prob;
            bestIdx  = i;
        } else if (prob > secondBest) {
            secondBest = prob;
        }
    }

    const float margin = bestProb - secondBest;

    Serial.print(F("Scores: "));
    for (int i = 0; i < classCount; i++) {
        Serial.print(CLASS_LABELS[i]);
        Serial.print(F("="));
        Serial.print(probs[i] * 100.0f, 1);
        if (i < classCount - 1) {
            Serial.print(F("%, "));
        }
    }
    Serial.println(F("%"));

    *outConfidence = bestProb;
    *outMargin     = margin;

    // Reject if background wins, confidence too low, or prediction is ambiguous.
    const bool hasBackgroundClass = (BACKGROUND_CLASS_IDX >= 0) &&
                                    (BACKGROUND_CLASS_IDX < classCount);

    if ((hasBackgroundClass && bestIdx == BACKGROUND_CLASS_IDX) ||
        bestProb < CONF_THRESH ||
        margin < MARGIN_THRESH) {
        return -1;
    }
    return bestIdx;
}

// =============================================================================
// Output helpers
// =============================================================================

static void blinkLED(int n) {
    for (int i = 0; i < n; i++) {
        digitalWrite(LED_BUILTIN, HIGH); delay(120);
        digitalWrite(LED_BUILTIN, LOW);  delay(120);
    }
}

static void reportDetection(int classIdx, float confidence) {
    Serial.print(F(">>> DETECTED: "));
    Serial.print(CLASS_LABELS[classIdx]);
    Serial.print(F("  conf="));
    Serial.print(confidence * 100.0f, 1);
    Serial.println(F("%"));
    blinkLED(BLINK_COUNT[classIdx]);
}

// =============================================================================
// Setup
// =============================================================================

void setup() {
    // Boot blink — visible even before Serial opens
    pinMode(LED_BUILTIN, OUTPUT);
    for (int i = 0; i < 6; i++) {
        digitalWrite(LED_BUILTIN, i % 2);
        delay(150);
    }

    Serial.begin(115200);
    const unsigned long serialAttachStart = millis();
    while (!Serial && (millis() - serialAttachStart < kSerialAttachTimeoutMs)) {
        delay(10);
    }
    delay(50);

    Serial.println(F("\n==================================="));
    Serial.println(F(" Gesture Detection — OV2640 + Nano33BLE"));
    Serial.println(F("==================================="));

    if (!initCamera()) {
        // Fast blink = camera error
        while (1) {
            digitalWrite(LED_BUILTIN, HIGH); delay(100);
            digitalWrite(LED_BUILTIN, LOW);  delay(100);
        }
    }

    if (!initTFLite()) {
        // Slow blink = TFLite error
        while (1) {
            digitalWrite(LED_BUILTIN, HIGH); delay(400);
            digitalWrite(LED_BUILTIN, LOW);  delay(400);
        }
    }

    Serial.print  (F("  Confidence threshold : "));
    Serial.print  (CONF_THRESH_PCT);
    Serial.println(F("%"));
    Serial.print  (F("  Margin threshold     : "));
    Serial.print  (MARGIN_THRESH_PCT);
    Serial.println(F("%"));
    Serial.print  (F("  Consensus frames     : "));
    Serial.println(CONSENSUS_FRAMES);
    Serial.print  (F("  Cooldown             : "));
    Serial.print  (COOLDOWN_MS);
    Serial.println(F(" ms"));
    Serial.println(F("Ready — show a gesture.\n"));
    Serial.println(F("[STATE] WAITING"));
    lastIdleReportMs = millis();
}

// =============================================================================
// Main loop — state machine (WAITING -> COOLDOWN -> WAITING)
// =============================================================================

void loop() {
    const uint32_t nowMs = millis();

    // ---- COOLDOWN: wait until timer expires, then return to WAITING ----
    if (currentState == COOLDOWN) {
        if (nowMs - lastTriggerMs >= (uint32_t)COOLDOWN_MS) {
            currentState = WAITING;
            lastIdleReportMs = nowMs;
            Serial.println(F("[STATE] WAITING"));
        }
        return;
    }

    // ---- WAITING: capture and infer ----
    if (!captureAndPreprocess()) {
        delay(500);
        return;
    }

    float confidence = 0.0f;
    float margin     = 0.0f;
    const unsigned long t0       = millis();
    const int           classIdx = runInference(&confidence, &margin);
    const unsigned long dt       = millis() - t0;

    if (classIdx < 0) {
        candidateClass = -1;
        candidateCount = 0;
        if (nowMs - lastIdleReportMs >= kIdleReportMs) {
            Serial.print(F("Waiting for gesture... last inference "));
            Serial.print(dt);
            Serial.print(F(" ms, frame hash=0x"));
            Serial.print(lastFrameHash, HEX);
            Serial.print(F(", y[min,max,mean]=["));
            Serial.print(frameLumaMin);
            Serial.print(F(","));
            Serial.print(frameLumaMax);
            Serial.print(F(","));
            Serial.print(frameLumaMean, 1);
            Serial.print(F("], q[min,max,mean]=["));
            Serial.print(frameQMin);
            Serial.print(F(","));
            Serial.print(frameQMax);
            Serial.print(F(","));
            Serial.print(frameQMean, 1);
            Serial.print(F("], input_hash=0x"));
            Serial.print(lastInputHash, HEX);
            Serial.print(F(", stable="));
            Serial.println(frameStableCount);

            if (frameStableCount > 5) {
                Serial.println(F("WARN: Camera frame appears unchanged across captures."));
            }
            lastIdleReportMs = nowMs;
        }
        return;
    }

    // ---- Temporal consensus filter ----
    if (classIdx == candidateClass) {
        if (candidateCount < 255) {
            candidateCount++;
        }
    } else {
        candidateClass = classIdx;
        candidateCount = 1;
    }

    if (candidateCount < CONSENSUS_FRAMES) {
        return;
    }

    // ---- Valid detection ----
    currentState  = COOLDOWN;
    lastTriggerMs = nowMs;
    candidateClass = -1;
    candidateCount = 0;

    reportDetection(classIdx, confidence);
    Serial.print  (F("  Margin        : "));
    Serial.print  (margin * 100.0f, 1);
    Serial.println(F("%"));

    Serial.print  (F("  Inference time: "));
    Serial.print  (dt);
    Serial.println(F(" ms"));
    Serial.print  (F("[STATE] COOLDOWN ("));
    Serial.print  (COOLDOWN_MS);
    Serial.println(F(" ms)"));
}
